### ISSUE TITLE
Postgres for WHOOSH_BASE?

### ISSUE THREAD

**Issue by Paberu** [Revolution1/Flask-WhooshAlchemyPlus#13]
Hi!
I'm using Postgresql for my project and I've decided to create another database at my server especially for Whoosh needs. Can Whoosh work with Postgres DB? I'm asking because I'm out of ideas, how to keep project in one piece.

**Comment by Revolution1** [comment]
Whoosh has no concern of which kind DB you use, nor do this project.

But, since the whoosh owner seems not maintaining it anymore, if you are looking for a full text search engine for production use, I suggest you just using the ElasticSearch.

Of course, for non-production, Whoosh and this plugin should work with Postgres.

**Comment by chis** [comment]
I came across Whooshalchemyplus and it really solved the problems I was having getting older versions to work, so thank you very much for this fork! 
I plan to use whooshplus in very small production (locally in an office, no internet). I think this will be adequate. Elasticsearch is too ram heavy for a RaspberryPi!
