### ISSUE TITLE
setup.py fails

### ISSUE THREAD

**Issue by geromueller** [Revolution1/Flask-WhooshAlchemyPlus#2]
Hi,

if whoosh is not installed, setup.py fails:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-build-r5Z410/flask-whooshalchemyplus/setup.py", line 11, in <module>
    from flask_whooshalchemyplus import __version__ as VERSION
  File "flask_whooshalchemyplus.py", line 25, in <module>
    import whoosh
ImportError: No module named whoosh
```

Importing the version.py is not a good idea. See here for a better solution: http://stackoverflow.com/a/24517154

Gero

**Comment by Revolution1** [comment]
Well, since this project only have one python file, it's a totally different situation from your "Solution".

This tool is built on the top of Whoosh, Flask and Flask_sqlalchemy. You need to install these dependencies before you run setup.py.

If you want these dependencies installed automatically, you can just `"pip install"` .
Don't worry, it's the same as `"setup.py install"`

Thank you for your advice.

Revol

**Comment by geromueller** [comment]
Hi,

the problem is, that pip install does not work, for the same reason.

**Comment by Revolution1** [comment]
Fixed.
Try pip it.

**Comment by geromueller** [comment]
Looks good. Thanks!
